# Generated by Django 2.1.7 on 2019-05-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='message',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
